name: scp files
on:
  push:
    branches: 
      - master
jobs:
  deploy-bot:
    name: deploy bot to server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "hey_cortona/"
        target: "~/bot"

  run-bot:
    name: Run bot
    runs-on: ubuntu-latest
    needs: deploy-bot
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo -E python3.8 "~/bot/hey-cortona/main.py"
            echo "running main.py"
    
    
