name: scp files
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    name: Copy folder content recursively to remote
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "hey_cortona/"
        target: "~/bot"
        script: |
          sudo -E python3.8 "~/bot/hey-cortona/main.py"
          echo "running main.py"
